### PR TITLE
Pipelines and docs for updating tWAS VM Images on RHEL 9.x

### PR DESCRIPTION
**Pull request by majguo**
## Description

The PR addresses most of the requirements listed in #64 by providing pipelines and docs for updating tWAS VM Images on RHEL 9.x in Azure Marketplace.

## Change summary

The following major changes are implemented:

* Refactor pipelines to fix some old issues (e.g., intermittent failure in resource cleanup)
* Install BigFix client for twas-nd and twas-base
* Harden the image by applying compatible rules using OpenSCAP tool
* Revert cis related pipelines and supporting files

## Testing

CICD pipelines for generating VHD files for tWAS VM Images on RHEL 9.x:
* [twas-base CICD](https://github.com/majguo/azure.websphere-traditional.image/actions/runs/4241813369)
* [twas-nd CICD](https://github.com/majguo/azure.websphere-traditional.image/actions/runs/4241815193)
* [ihs CICD](https://github.com/majguo/azure.websphere-traditional.image/actions/runs/4241817431)

These generated VHD files are also used for updating the [testing tWAS VM offer](https://partner.microsoft.com/en-us/dashboard/commercial-marketplace/offers/387cd9d3-f4ca-454b-9a89-c612fffe29d6/overview) in PartnerCenter. The [testing tWAS VM offer](https://partner.microsoft.com/en-us/dashboard/commercial-marketplace/offers/387cd9d3-f4ca-454b-9a89-c612fffe29d6/overview) is successfully published and in preview, which is verified by deploying VM from both Azure Portal and solution template. The preview links for creating VMs:

* [twas-base](https://portal.azure.com/?feature.customportal=false#create/microsoft_javaeeonazure_test.2021-zheng-image-offer-preview2021-zheng-rhel-with-was-base)
* [twas-nd](https://portal.azure.com/?feature.customportal=false#create/microsoft_javaeeonazure_test.2021-zheng-image-offer-preview2021-zheng-rhel-with-websphere)
* [ihs](https://portal.azure.com/?feature.customportal=false#create/microsoft_javaeeonazure_test.2021-zheng-image-offer-preview2021-zheng-rhel-with-ihs)

## How-To docs

Part of how-to docs of updating the VM images are located in the following PRs: 

* WASdev/azure.websphere-traditional.singleserver/pull/70
* WASdev/azure.websphere-traditional.cluster/pull/207

The others are included in this PR.

As a result, after the above PRs and this PR are merged, instructions on how to update tWAS VM images on RHEL 9.x can be referenced from [howto-update-image.md](https://github.com/WASdev/azure.websphere-traditional.image/blob/main/docs/howto-update-image.md).

### Partner center HTML

I drafted contents of Azure virtual machine offer as requested, they're located in:

* ihs/src/main/resources/marketing-artifacts/partner-center.html
* twas-base/src/main/resources/marketing-artifacts/partner-center.html
* twas-nd/src/main/resources/marketing-artifacts/partner-center.html

@gcharters @git4rk @m-reza-rahman @edburns, pls continue working on it when updating vm offers in partner center.

## OpenSCAP reports

The scanning reports before and after compliance remediation can be downloaded from the summary of pipeline workflow, e.g.:

* [scan-report-before](https://github.com/majguo/azure.websphere-traditional.image/suites/11131134872/artifacts/567637363)
  image
* [scan-report-after](https://github.com/majguo/azure.websphere-traditional.image/suites/11131134872/artifacts/567637362)
  image

**Note**:  after applying OpenSCAP rules, additional commands (e.g., `waagent -deprovision+user -force`) have to be executed for generating Azure VM image. The followings are what `waagent -deprovision+user -force` does during the execution:
```
waagent -deprovision+user -force
WARNING! The waagent service will be stopped.
WARNING! All SSH host key pairs will be deleted.
WARNING! Cached DHCP leases will be deleted.
WARNING! root password will be disabled. You will not be able to login as root.
WARNING! /etc/resolv.conf will be deleted.
WARNING! <admin-account-name> account and entire home directory will be deleted.
2023-02-21T00:57:42.690257Z INFO MainThread Examine /proc/net/route for primary interface
2023-02-21T00:57:42.690784Z INFO MainThread Primary interface is [eth0]
```

Besides, VM creation may also introduce some difference regarding to security. So I deployed a new VM with [twas-base](https://portal.azure.com/?feature.customportal=false#create/microsoft_javaeeonazure_test.2021-zheng-image-offer-preview2021-zheng-rhel-with-was-base) and ran the scanning again, there is only slight difference between reports, which should be acceptable:

* [scan_report_vmCreatedFromHardenedImage.zip](https://github.com/WASdev/azure.websphere-traditional.image/files/10820382/scan_report_vmCreatedFromHardenedImage.zip)
  image

Signed-off-by: Jianguo Ma <jiangma@microsoft.com>

### CODE REVIEW

**Comment by majguo** [comment]
Hello @venunathb Could you pls review the PR? Thanks.

**Comment by venunathb** [comment]
@majguo Do we have `Openscap` reports links in CICD pipelines? If yes, how to access them?

I see the following on the CICD summary page, but I need help finding the ink to the `Openscap` report.
image


[twas-base CICD](https://github.com/majguo/azure.websphere-traditional.image/actions/runs/4241813369)
[twas-nd CICD](https://github.com/majguo/azure.websphere-traditional.image/actions/runs/4241815193)
[ihs CICD](https://github.com/majguo/azure.websphere-traditional.image/actions/runs/4241817431)

**Comment by venunathb** [comment]
PR review.

- [ ] Refactor pipelines to fix some old issues (e.g., intermittent failure in resource cleanup)
- [ ] Install BigFix client for twas-nd and twas-base
- [ ] Harden the image by applying compatible rules using OpenSCAP tool
- [ ] Revert cis related pipelines and supporting files
- [ ] How to Docs
- [ ] Deploy VM using preview links.

**Comment by majguo** [comment]
> @majguo Do we have `Openscap` reports links in CICD pipelines? If yes, how to access them?
> 
> I see the following on the CICD summary page, but I need help finding the ink to the `Openscap` report. image
> 
> [twas-base CICD](https://github.com/majguo/azure.websphere-traditional.image/actions/runs/4241813369) 
> [twas-nd CICD](https://github.com/majguo/azure.websphere-traditional.image/actions/runs/4241815193) 
> [ihs CICD](https://github.com/majguo/azure.websphere-traditional.image/actions/runs/4241817431)

@venunathb Yes, we have. Follow steps below to access them:
1. Click to open workflow ran [twas-base CICD](https://github.com/majguo/azure.websphere-traditional.image/actions/runs/4241813369) mentioned in the PR. The **Summary** will be displayed.
1. Scroll down to the bottom of the page.
1. In **Artifacts** section, there're two links for OpenSCAP reports: scan-report-before and scan-report-after.
1. Click links to download reports.

Same steps for accessing reports for [twas-nd CICD](https://github.com/majguo/azure.websphere-traditional.image/actions/runs/4241815193)  and [ihs CICD](https://github.com/majguo/azure.websphere-traditional.image/actions/runs/4241817431)

**Pull request merged**
